# Generated by Django 6.0.1 on 2026-01-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, unique=True)),
                ('capacity', models.PositiveIntegerField(default=4, max_length=3)),
                ('status', models.CharField(choices=[('FREE', 'Libre'), ('BUSY', 'Ocupada'), ('RSVD', 'Reservada'), ('CLN', 'Limpieza')], default='FREE', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
            },
        ),
    ]
