# Generated by Django 6.0.1 on 2026-01-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_category_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
